apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-pkl
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-pkl
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Pkl
      spec:
        crds:
          - apiVersion: example.crossplane.io/v1
            kind: XR
            uri: "@example/crds/XR.pkl"
          - apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            uri: "@example/crds/Object.pkl"
        full:
          name: object-one
          type: uri
          uri: "@example/object-one.pkl"
        packages:
          - name: core
            core: true
            uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane@0.0.23
          - name: example
            uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.1.7
