apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-pkl
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-pkl
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Pkl
      spec:
        crds:
          - apiVersion: example.crossplane.io/v1
            kind: XR
            uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.1.3#/crds/XR.pkl
          - apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.1.3#/crds/Object.pkl
        composition:
          name: XR
          type: uri
          uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.1.3#/xr.pkl
        resources:
          - name: object-one
            type: uri
            uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.1.3#/object-one.pkl
          - name: object-two
            type: uri
            uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.1.3#/object-two.pkl
