apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-pkl
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-pkl
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Pkl
      spec:
        pklCRDs:
          - apiVersion: example.crossplane.io/v1
            kind: XR
            uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.0.7#/crds/XR.pkl
          - apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.0.7#/crds/Object.pkl
        pklComposition:
          name: XR
          type: uri
          uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.0.7#/crds/XR.pkl
        pklManifests:
          - name: object-one
            type: uri
            uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.0.7#/object-one.pkl
          - name: object-two
            type: uri
            uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.0.7#/object-two.pkl
#          - name: object-needs-extra-resource
#            type: uri
#            uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.0.7#/object-needs-extra-resource.pkl
#        requirements:
#          name: extra-resource
#          type: uri
#          uri: package://pkg.pkl-lang.org/github.com/avarei/function-pkl/crossplane-example@0.0.7#/extra-resource.pkl
